version: '2.2'

services:

  telegram_bot:
    build: 
      context: .
      dockerfile: toub.dockerfile
    command: tail -f /dev/null
    volumes:
      - ./photos:/usr/src/app/photos
      - ./src:/usr/src/app
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
      - $HOME/.npmrc:/home/node/.npmrc
    ports:
      - 3000:3000
    environment:
      - GALLERY_URL
      - PHOTOS_DIRECTORY
      - TELEGRAM_BOT_TOKEN
      - REDIS_HOST
      - REDIS_PORT
      - EVENT_DOC_URL
      - EVENT_GAMES_PREFIX
      - PLAYLIST_URL
    links:
      - database:redis

  database:
    image: redis:alpine
    entrypoint:
      - 'redis-server'
      - '--appendonly'
      - 'yes'
    volumes:
    - redis-data:/data

  db_admin:
    image: diyan/redis-commander:latest
    entrypoint:
      - 'redis-commander'
      - '--redis-host'
      - 'redis'
    ports:
      - 8081:8081
    links:
      - database:redis

volumes:
  redis-data:
  photos:
